import { context, build } from 'esbuild'

/**
 * Bundles extension/src/content-script.ts (which pulls in client/voice/stt.ts
 * and api.ts - real files with real imports, the reason this build step
 * exists at all) into extension/content-script.js, which the manifest loads
 * directly as a classic (non-module) content script.
 *
 * background.js has no imports and stays a plain hand-written file - not
 * worth routing through a bundler.
 */
const options = {
	entryPoints: ['extension/src/content-script.ts'],
	outfile: 'extension/content-script.js',
	bundle: true,
	format: 'iife',
	target: 'es2020',
	logLevel: 'info',
	banner: { js: '// GENERATED by extension/build.mjs from extension/src/content-script.ts - do not edit directly.' },
}

if (process.argv.includes('--watch')) {
	const ctx = await context(options)
	await ctx.watch()
	console.log('watching extension/src for changes...')
} else {
	await build(options)
}
