import { context, build } from 'esbuild'

/**
 * Bundles every extension/src/*.ts entry point into its sibling .js file at
 * extension/, which the manifest loads directly: content-script (box-select
 * + voice UI), background (bring-your-own-key generation, owns the API
 * key(s)), options (API key entry), render (the sandboxed page that runs
 * model-generated HTML).
 *
 * Chart.js/Mermaid/KaTeX/Stepper (extension/vendor/) are committed directly
 * here, not generated by this script - there used to be a public/vendor/
 * "source" copy that this build step synced into extension/vendor/ on every
 * run, but the two were always byte-identical and nothing else ever read
 * public/vendor/, so it was pure duplication (14MB of committed binaries for
 * one logical set of files). Removed; edit extension/vendor/ directly if a
 * vendored library ever needs updating.
 */
const entryPoints = ['content-script', 'background', 'options', 'render']

const options = {
	entryPoints: entryPoints.map((name) => `extension/src/${name}.ts`),
	outdir: 'extension',
	outbase: 'extension/src',
	entryNames: '[name]',
	bundle: true,
	// Minified: the background service worker (1.3MB of AI SDK) is re-parsed on every cold start.
	minify: true,
	format: 'iife',
	target: 'es2022',
	logLevel: 'info',
	banner: { js: '// GENERATED by extension/build.mjs - do not edit directly.' },
}

if (process.argv.includes('--watch')) {
	const ctx = await context(options)
	await ctx.watch()
	console.log('watching extension/src for changes...')
} else {
	await build(options)
}
