import { context, build } from 'esbuild'
import { cpSync, mkdirSync } from 'node:fs'

/**
 * Bundles every extension/src/*.ts entry point into its sibling .js file at
 * extension/, which the manifest loads directly. Four entry points as of
 * Phase 5/6: content-script (box-select + voice UI), background (now also
 * does bring-your-own-key generation, so it needs bundling too), options
 * (API key entry), render (the sandboxed page that runs model-generated HTML).
 */
const entryPoints = ['content-script', 'background', 'options', 'render']

const options = {
	entryPoints: entryPoints.map((name) => `extension/src/${name}.ts`),
	outdir: 'extension',
	outbase: 'extension/src',
	entryNames: '[name]',
	bundle: true,
	format: 'iife',
	target: 'es2022',
	logLevel: 'info',
	banner: { js: '// GENERATED by extension/build.mjs - do not edit directly.' },
}

/**
 * Chart.js/Mermaid/KaTeX/Stepper ship as real files inside the extension
 * package (see manifest.json's web_accessible_resources) rather than being
 * fetched from a worker or a CDN - a few MB in an extension bundle is a
 * non-issue, unlike a few MB on every network response. axe-core is a
 * leftover from the pre-pivot tldraw canvas app's accessibility testing and
 * has no use here, so it's deliberately excluded.
 */
function copyVendor() {
	// Overwrite-in-place rather than rmSync+recreate: Dropbox's sync agent
	// intermittently holds a lock on the vendor dir on Windows, which makes
	// rmSync fail with EPERM even though nothing else is actually using the
	// files. cpSync's force+recursive overwrite doesn't need the dir gone
	// first, so it sidesteps the lock entirely.
	mkdirSync('extension/vendor', { recursive: true })
	for (const lib of ['chartjs', 'katex', 'mermaid', 'stepper']) {
		cpSync(`public/vendor/${lib}`, `extension/vendor/${lib}`, { recursive: true, force: true })
	}
}

copyVendor()

if (process.argv.includes('--watch')) {
	const ctx = await context(options)
	await ctx.watch()
	console.log('watching extension/src for changes...')
} else {
	await build(options)
}
