// GENERATED by extension/build.mjs from extension/src/content-script.ts - do not edit directly.
"use strict";
(() => {
  var __defProp = Object.defineProperty;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

  // client/voice/api.ts
  var TOKEN_KEY = "whiteboard-tutor:access-token";
  var SESSION_KEY = "whiteboard-tutor:session-id";
  function getAccessToken() {
    try {
      return localStorage.getItem(TOKEN_KEY) ?? "";
    } catch {
      return "";
    }
  }
  var sessionId = "";
  function getSessionId() {
    if (sessionId) return sessionId;
    try {
      sessionId = sessionStorage.getItem(SESSION_KEY) ?? "";
    } catch {
    }
    if (!sessionId) {
      sessionId = crypto.randomUUID().replace(/-/g, "");
      try {
        sessionStorage.setItem(SESSION_KEY, sessionId);
      } catch {
      }
    }
    return sessionId;
  }
  function apiFetch(path, init = {}) {
    const headers = new Headers(init.headers);
    headers.set("x-session-id", getSessionId());
    const token = getAccessToken();
    if (token) headers.set("Authorization", `Bearer ${token}`);
    return fetch(path, { ...init, headers });
  }

  // client/voice/stt.ts
  function getSpeechRecognitionCtor() {
    const w = window;
    return w.SpeechRecognition ?? w.webkitSpeechRecognition ?? null;
  }
  function isBrowserSttSupported() {
    return typeof window !== "undefined" && getSpeechRecognitionCtor() !== null;
  }
  var AUTO_SEND_AFTER_MS = 1500;
  var BrowserStt = class {
    constructor(callbacks) {
      __publicField(this, "callbacks", callbacks);
      __publicField(this, "recognition", null);
      __publicField(this, "finalText", "");
      __publicField(this, "autoSendTimer", null);
    }
    async start() {
      const Ctor = getSpeechRecognitionCtor();
      if (!Ctor) {
        this.callbacks.onError("This browser has no built-in speech recognition. Switch to OpenAI.");
        this.callbacks.onEnd();
        return;
      }
      const rec = new Ctor();
      rec.lang = navigator.language || "en-US";
      rec.continuous = true;
      rec.interimResults = true;
      rec.maxAlternatives = 1;
      this.finalText = "";
      rec.onresult = (e) => {
        let interim = "";
        let gotFinal = false;
        for (let i = e.resultIndex; i < e.results.length; i++) {
          const result = e.results[i];
          const transcript = result[0]?.transcript ?? "";
          if (result.isFinal) {
            this.finalText += transcript + " ";
            gotFinal = true;
          } else {
            interim += transcript;
          }
        }
        this.callbacks.onInterim?.((this.finalText + interim).trim());
        if (this.autoSendTimer) clearTimeout(this.autoSendTimer);
        if (gotFinal && !interim) {
          this.autoSendTimer = setTimeout(() => this.stop(), AUTO_SEND_AFTER_MS);
        }
      };
      rec.onerror = (e) => {
        if (e?.error === "no-speech" || e?.error === "aborted") return;
        this.callbacks.onError(`Speech recognition error: ${e?.error ?? "unknown"}`);
      };
      rec.onend = () => {
        if (this.autoSendTimer) clearTimeout(this.autoSendTimer);
        this.autoSendTimer = null;
        const text = this.finalText.trim();
        this.recognition = null;
        if (text) this.callbacks.onFinal(text);
        this.callbacks.onEnd();
      };
      this.recognition = rec;
      rec.start();
    }
    stop() {
      this.recognition?.stop();
    }
    abort() {
      const rec = this.recognition;
      this.recognition = null;
      if (rec) {
        rec.onend = null;
        rec.abort();
        this.callbacks.onEnd();
      }
    }
  };
  var RecordedClipStt = class {
    constructor(callbacks) {
      __publicField(this, "callbacks", callbacks);
      __publicField(this, "recorder", null);
      __publicField(this, "stream", null);
      __publicField(this, "chunks", []);
      __publicField(this, "aborted", false);
    }
    async start() {
      try {
        this.stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      } catch {
        this.callbacks.onError("Microphone permission was denied.");
        this.callbacks.onEnd();
        return;
      }
      const mimeType = MediaRecorder.isTypeSupported("audio/webm") ? "audio/webm" : "";
      const recorder = new MediaRecorder(this.stream, mimeType ? { mimeType } : void 0);
      this.chunks = [];
      this.aborted = false;
      recorder.ondataavailable = (e) => {
        if (e.data.size > 0) this.chunks.push(e.data);
      };
      recorder.onstop = async () => {
        this.stream?.getTracks().forEach((t) => t.stop());
        this.stream = null;
        this.recorder = null;
        if (this.aborted) {
          this.callbacks.onEnd();
          return;
        }
        const blob = new Blob(this.chunks, { type: recorder.mimeType || "audio/webm" });
        this.chunks = [];
        if (blob.size < 2e3) {
          this.callbacks.onEnd();
          return;
        }
        try {
          const form = new FormData();
          form.append("audio", blob, "clip.webm");
          const res = await apiFetch(this.endpoint, { method: "POST", body: form });
          if (!res.ok) throw new Error(await res.text());
          const { text } = await res.json();
          if (text?.trim()) this.callbacks.onFinal(text.trim());
        } catch (e) {
          this.callbacks.onError(e?.message ?? "Transcription failed");
        } finally {
          this.callbacks.onEnd();
        }
      };
      this.recorder = recorder;
      recorder.start();
      this.callbacks.onInterim?.("Recording\u2026 click the mic again when you are done.");
    }
    stop() {
      if (this.recorder && this.recorder.state !== "inactive") this.recorder.stop();
    }
    abort() {
      this.aborted = true;
      this.stop();
    }
  };
  var OpenAiStt = class extends RecordedClipStt {
    constructor() {
      super(...arguments);
      __publicField(this, "endpoint", "/transcribe");
    }
  };
  var GroqStt = class extends RecordedClipStt {
    constructor() {
      super(...arguments);
      __publicField(this, "endpoint", "/transcribe-groq");
    }
  };
  function createStt(engine, callbacks) {
    if (engine === "openai") return new OpenAiStt(callbacks);
    if (engine === "groq") return new GroqStt(callbacks);
    return new BrowserStt(callbacks);
  }

  // extension/src/content-script.ts
  var mode = "idle";
  var overlayEl = null;
  var badgeEl = null;
  var boxEl = null;
  var panelEl = null;
  var stt = null;
  var startX = 0;
  var startY = 0;
  var activeMatches = null;
  var activeRect = null;
  function enterSelectMode() {
    closeEverything();
    mode = "selecting";
    const overlay = document.createElement("div");
    Object.assign(overlay.style, {
      position: "fixed",
      inset: "0",
      zIndex: "2147483647",
      cursor: "crosshair",
      background: "rgba(0,0,0,0.02)"
    });
    overlay.addEventListener("mousedown", onMouseDown);
    document.documentElement.appendChild(overlay);
    overlayEl = overlay;
    setBadge("Circle-select active \u2014 drag a box, Esc to cancel");
    document.addEventListener("keydown", onKeyDown);
  }
  function setBadge(text) {
    badgeEl?.remove();
    const badge = document.createElement("div");
    badge.textContent = text;
    Object.assign(badge.style, {
      position: "fixed",
      top: "12px",
      left: "50%",
      transform: "translateX(-50%)",
      background: "#1a1a1a",
      color: "#fff",
      padding: "6px 14px",
      borderRadius: "6px",
      fontFamily: "system-ui, sans-serif",
      fontSize: "13px",
      zIndex: "2147483647",
      pointerEvents: "none",
      boxShadow: "0 2px 8px rgba(0,0,0,0.3)"
    });
    document.documentElement.appendChild(badge);
    badgeEl = badge;
  }
  function exitSelectMode() {
    overlayEl?.remove();
    badgeEl?.remove();
    boxEl?.remove();
    document.removeEventListener("keydown", onKeyDown);
    overlayEl = badgeEl = boxEl = null;
  }
  function closeEverything() {
    stt?.abort();
    stt = null;
    exitSelectMode();
    panelEl?.remove();
    panelEl = null;
    activeMatches = null;
    activeRect = null;
    mode = "idle";
  }
  function onKeyDown(e) {
    if (e.key !== "Escape") return;
    if (mode === "listening") {
      stt?.abort();
      stt = null;
      mode = "idle";
      if (activeRect && activeMatches) {
        showPanel(activeRect, `${matchSummary(activeMatches)}

(listening cancelled)`);
      }
      return;
    }
    closeEverything();
  }
  function onMouseDown(e) {
    startX = e.clientX;
    startY = e.clientY;
    boxEl = document.createElement("div");
    Object.assign(boxEl.style, {
      position: "fixed",
      border: "2px solid #3b82f6",
      background: "rgba(59,130,246,0.15)",
      zIndex: "2147483647",
      pointerEvents: "none"
    });
    document.documentElement.appendChild(boxEl);
    document.addEventListener("mousemove", onMouseMove);
    document.addEventListener("mouseup", onMouseUp);
    e.preventDefault();
  }
  function onMouseMove(e) {
    if (!boxEl) return;
    const x = Math.min(startX, e.clientX);
    const y = Math.min(startY, e.clientY);
    const w = Math.abs(e.clientX - startX);
    const h = Math.abs(e.clientY - startY);
    Object.assign(boxEl.style, { left: x + "px", top: y + "px", width: w + "px", height: h + "px" });
  }
  function onMouseUp() {
    document.removeEventListener("mousemove", onMouseMove);
    document.removeEventListener("mouseup", onMouseUp);
    const rect = boxEl?.getBoundingClientRect();
    exitSelectMode();
    if (!rect || rect.width < 4 || rect.height < 4) {
      mode = "idle";
      return;
    }
    const matches = findMatches(rect);
    if (matches.length === 0) {
      showPanel(rect, "No tagged elements in that box.\n(Only elements served by the Phase 1 source-tagging dev plugin are selectable.)");
      mode = "idle";
      return;
    }
    activeMatches = matches;
    activeRect = rect;
    startListening(rect, matches);
  }
  function findMatches(selectionRect) {
    const candidates = document.querySelectorAll("[data-src-start][data-src-end]");
    const results = [];
    for (const el of candidates) {
      const r = el.getBoundingClientRect();
      const ix = Math.max(0, Math.min(r.right, selectionRect.right) - Math.max(r.left, selectionRect.left));
      const iy = Math.max(0, Math.min(r.bottom, selectionRect.bottom) - Math.max(r.top, selectionRect.top));
      const intersection = ix * iy;
      if (intersection <= 0) continue;
      const ownArea = Math.max(1, r.width * r.height);
      results.push({
        el,
        coverage: intersection / ownArea,
        area: ownArea,
        start: Number(el.getAttribute("data-src-start")),
        end: Number(el.getAttribute("data-src-end"))
      });
    }
    results.sort((a, b) => b.coverage - a.coverage || a.area - b.area);
    return results;
  }
  function describe(el) {
    const tag = el.tagName.toLowerCase();
    const id = el.id ? "#" + el.id : "";
    const cls = el.classList.length ? "." + Array.from(el.classList).join(".") : "";
    return tag + id + cls;
  }
  function matchSummary(matches) {
    const best = matches[0];
    const preview = (best.el.textContent ?? "").trim().replace(/\s+/g, " ").slice(0, 80);
    return `Selected: ${describe(best.el)}
source range: [${best.start}, ${best.end})
content: "${preview}${preview.length === 80 ? "\u2026" : ""}"` + (matches.length > 1 ? `
(${matches.length - 1} other candidate(s) also in the box)` : "");
  }
  function startListening(rect, matches) {
    mode = "listening";
    const engine = isBrowserSttSupported() ? "browser" : "groq";
    let interim = "";
    showPanel(rect, `${matchSummary(matches)}

\u{1F3A4} Listening\u2026`);
    stt = createStt(engine, {
      onInterim(text) {
        interim = text;
        showPanel(rect, `${matchSummary(matches)}

\u{1F3A4} Listening\u2026 "${interim}"`);
      },
      onFinal(text) {
        showPanel(rect, `${matchSummary(matches)}

\u2705 Heard: "${text}"

(Phase 4 will turn this into a visualization.)`);
      },
      onError(message) {
        showPanel(rect, `${matchSummary(matches)}

\u26A0\uFE0F ${message}`);
      },
      onEnd() {
        stt = null;
        mode = "idle";
      }
    });
    void stt.start();
  }
  function showPanel(selectionRect, text) {
    panelEl?.remove();
    const panel = document.createElement("div");
    Object.assign(panel.style, {
      position: "fixed",
      zIndex: "2147483647",
      maxWidth: "420px",
      background: "#1a1a1a",
      color: "#e5e5e5",
      padding: "12px 14px",
      borderRadius: "8px",
      fontFamily: "ui-monospace, monospace",
      fontSize: "12px",
      lineHeight: "1.5",
      boxShadow: "0 4px 16px rgba(0,0,0,0.4)",
      whiteSpace: "pre-wrap",
      overflowY: "auto"
    });
    const margin = 8;
    const spaceBelow = window.innerHeight - selectionRect.bottom - margin;
    const spaceAbove = selectionRect.top - margin;
    const placeAbove = spaceBelow < 120 && spaceAbove > spaceBelow;
    panel.style.maxHeight = Math.max(100, (placeAbove ? spaceAbove : spaceBelow) - margin) + "px";
    if (placeAbove) {
      panel.style.bottom = window.innerHeight - selectionRect.top + margin + "px";
    } else {
      panel.style.top = selectionRect.bottom + margin + "px";
    }
    panel.style.left = Math.min(Math.max(8, selectionRect.left), window.innerWidth - 440) + "px";
    panel.textContent = text;
    document.documentElement.appendChild(panel);
    panelEl = panel;
    panel.scrollTop = panel.scrollHeight;
  }
  chrome.runtime.onMessage.addListener((message) => {
    if (message?.type !== "toggle-overlay") return;
    if (mode !== "idle") closeEverything();
    else enterSelectMode();
  });
})();
