// GENERATED by extension/build.mjs - do not edit directly.
"use strict";
(() => {
  // shared/voice/stt.ts
  function getSpeechRecognitionCtor() {
    const w = window;
    return w.SpeechRecognition ?? w.webkitSpeechRecognition ?? null;
  }
  var AUTO_SEND_AFTER_MS = 1500;
  function describeSttError(code) {
    switch (code) {
      case "not-allowed":
      case "service-not-allowed":
        return "Microphone access is blocked for this page. Click the lock/camera icon in the address bar, allow the microphone, then try again - permission is granted per-site, so a page you haven't used this on before needs it granted once.";
      case "audio-capture":
        return "No microphone found, or it\u2019s in use by another app. Check your mic and try again.";
      case "network":
        return "Speech recognition needs a network connection (Chrome's speech-to-text runs server-side) - check your connection and try again.";
      default:
        return `Speech recognition error: ${code ?? "unknown"}`;
    }
  }
  var BrowserStt = class {
    constructor(callbacks) {
      this.callbacks = callbacks;
    }
    callbacks;
    recognition = null;
    finalText = "";
    autoSendTimer = null;
    async start() {
      const Ctor = getSpeechRecognitionCtor();
      if (!Ctor) {
        this.callbacks.onError("This browser has no built-in speech recognition.");
        this.callbacks.onEnd();
        return;
      }
      const rec = new Ctor();
      rec.lang = navigator.language || "en-US";
      rec.continuous = true;
      rec.interimResults = true;
      rec.maxAlternatives = 1;
      this.finalText = "";
      rec.onresult = (e) => {
        let interim = "";
        let gotFinal = false;
        for (let i = e.resultIndex; i < e.results.length; i++) {
          const result = e.results[i];
          const transcript = result[0]?.transcript ?? "";
          if (result.isFinal) {
            this.finalText += transcript + " ";
            gotFinal = true;
          } else {
            interim += transcript;
          }
        }
        this.callbacks.onInterim?.((this.finalText + interim).trim());
        if (this.autoSendTimer) clearTimeout(this.autoSendTimer);
        if (gotFinal && !interim) {
          this.autoSendTimer = setTimeout(() => this.stop(), AUTO_SEND_AFTER_MS);
        }
      };
      rec.onerror = (e) => {
        if (e?.error === "no-speech" || e?.error === "aborted") return;
        this.callbacks.onError(describeSttError(e?.error));
      };
      rec.onend = () => {
        if (this.autoSendTimer) clearTimeout(this.autoSendTimer);
        this.autoSendTimer = null;
        const text = this.finalText.trim();
        this.recognition = null;
        if (text) this.callbacks.onFinal(text);
        this.callbacks.onEnd();
      };
      this.recognition = rec;
      rec.start();
    }
    stop() {
      this.recognition?.stop();
    }
    abort() {
      const rec = this.recognition;
      this.recognition = null;
      if (rec) {
        rec.onend = null;
        rec.abort();
        this.callbacks.onEnd();
      }
    }
  };
  function createStt(callbacks) {
    return new BrowserStt(callbacks);
  }

  // extension/src/content-script.ts
  var mode = "idle";
  var overlayEl = null;
  var badgeEl = null;
  var boxEl = null;
  var panelEl = null;
  var stt = null;
  var startX = 0;
  var startY = 0;
  var activeMatches = null;
  var activeRect = null;
  var activeImagePromise = null;
  var draggedPosition = null;
  var panelDragCleanup = null;
  var panelVoiceCleanup = null;
  function makeDraggable(el, handle = el) {
    let dragging = false;
    let offsetX = 0;
    let offsetY = 0;
    const onMouseDown2 = (e) => {
      dragging = true;
      const rect = el.getBoundingClientRect();
      offsetX = e.clientX - rect.left;
      offsetY = e.clientY - rect.top;
      e.preventDefault();
    };
    const onMouseMove2 = (e) => {
      if (!dragging) return;
      const left = Math.min(Math.max(0, e.clientX - offsetX), window.innerWidth - el.offsetWidth);
      const top = Math.min(Math.max(0, e.clientY - offsetY), window.innerHeight - el.offsetHeight);
      el.style.left = left + "px";
      el.style.top = top + "px";
      el.style.right = "";
      el.style.bottom = "";
      draggedPosition = { top, left };
    };
    const onMouseUp2 = () => {
      dragging = false;
    };
    handle.style.cursor = "move";
    handle.addEventListener("mousedown", onMouseDown2);
    document.addEventListener("mousemove", onMouseMove2);
    document.addEventListener("mouseup", onMouseUp2);
    return () => {
      document.removeEventListener("mousemove", onMouseMove2);
      document.removeEventListener("mouseup", onMouseUp2);
    };
  }
  function enterSelectMode() {
    closeEverything();
    mode = "selecting";
    const overlay = document.createElement("div");
    Object.assign(overlay.style, {
      position: "fixed",
      inset: "0",
      zIndex: "2147483647",
      cursor: "crosshair",
      background: "rgba(0,0,0,0.02)"
    });
    overlay.addEventListener("mousedown", onMouseDown);
    document.documentElement.appendChild(overlay);
    overlayEl = overlay;
    setBadge("Circle-select active \u2014 drag a box, Esc to cancel");
    document.addEventListener("keydown", onKeyDown);
  }
  function setBadge(text) {
    badgeEl?.remove();
    const badge = document.createElement("div");
    badge.textContent = "\u25CE " + text;
    Object.assign(badge.style, {
      position: "fixed",
      top: "12px",
      left: "50%",
      transform: "translateX(-50%)",
      background: "#1a1a1a",
      color: "#fff",
      padding: "7px 16px",
      borderRadius: "20px",
      fontFamily: "system-ui, sans-serif",
      fontSize: "13px",
      zIndex: "2147483647",
      pointerEvents: "none",
      boxShadow: "0 2px 10px rgba(0,0,0,0.35)"
    });
    document.documentElement.appendChild(badge);
    badgeEl = badge;
  }
  function exitSelectMode() {
    overlayEl?.remove();
    badgeEl?.remove();
    boxEl?.remove();
    document.removeEventListener("keydown", onKeyDown);
    overlayEl = badgeEl = boxEl = null;
  }
  function closeEverything() {
    stt?.abort();
    stt = null;
    exitSelectMode();
    panelDragCleanup?.();
    panelDragCleanup = null;
    panelVoiceCleanup?.();
    panelVoiceCleanup = null;
    draggedPosition = null;
    panelEl?.remove();
    panelEl = null;
    activeMatches = null;
    activeRect = null;
    activeImagePromise = null;
    mode = "idle";
  }
  function onKeyDown(e) {
    if (e.key !== "Escape") return;
    if (mode === "listening") {
      stt?.abort();
      stt = null;
      mode = "idle";
      if (activeRect && activeMatches) {
        showPanel(activeRect, `${matchSummary(activeMatches)}

(listening cancelled)`);
      }
      return;
    }
    closeEverything();
  }
  function onMouseDown(e) {
    startX = e.clientX;
    startY = e.clientY;
    boxEl = document.createElement("div");
    Object.assign(boxEl.style, {
      position: "fixed",
      border: "2px solid #3b82f6",
      background: "rgba(59,130,246,0.15)",
      zIndex: "2147483647",
      pointerEvents: "none"
    });
    document.documentElement.appendChild(boxEl);
    document.addEventListener("mousemove", onMouseMove);
    document.addEventListener("mouseup", onMouseUp);
    e.preventDefault();
  }
  function onMouseMove(e) {
    if (!boxEl) return;
    const x = Math.min(startX, e.clientX);
    const y = Math.min(startY, e.clientY);
    const w = Math.abs(e.clientX - startX);
    const h = Math.abs(e.clientY - startY);
    Object.assign(boxEl.style, { left: x + "px", top: y + "px", width: w + "px", height: h + "px" });
  }
  function onMouseUp() {
    document.removeEventListener("mousemove", onMouseMove);
    document.removeEventListener("mouseup", onMouseUp);
    const rect = boxEl?.getBoundingClientRect();
    exitSelectMode();
    if (!rect || rect.width < 4 || rect.height < 4) {
      mode = "idle";
      return;
    }
    const matches = findMatches(rect);
    if (matches.length === 0) {
      showPanel(rect, "Nothing selectable in that box - try circling some text or a visible element.");
      mode = "idle";
      return;
    }
    activeMatches = matches;
    activeRect = rect;
    activeImagePromise = needsVision(matches[0].el) ? captureSelectionImage(rect) : Promise.resolve(null);
    startListening(rect, matches);
  }
  function needsVision(el) {
    if (el.tagName === "IMG" || el.tagName === "CANVAS" || el.tagName === "SVG") return true;
    return (el.textContent ?? "").trim().length === 0;
  }
  async function captureSelectionImage(rect) {
    try {
      const relay = await chrome.runtime.sendMessage({ type: "capture-tab" });
      if (!relay.ok || !relay.dataUrl) return null;
      const img = new Image();
      const loaded = new Promise((resolve, reject) => {
        img.onload = () => resolve();
        img.onerror = () => reject(new Error("Screenshot failed to load"));
      });
      img.src = relay.dataUrl;
      await loaded;
      const dpr = window.devicePixelRatio || 1;
      const w = Math.max(1, Math.round(rect.width * dpr));
      const h = Math.max(1, Math.round(rect.height * dpr));
      const canvas = document.createElement("canvas");
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext("2d");
      if (!ctx) return null;
      ctx.drawImage(img, Math.round(rect.left * dpr), Math.round(rect.top * dpr), w, h, 0, 0, w, h);
      return canvas.toDataURL("image/png").split(",")[1] ?? null;
    } catch {
      return null;
    }
  }
  function findMatches(selectionRect) {
    const SAMPLES_PER_AXIS = 5;
    const counts = /* @__PURE__ */ new Map();
    for (let i = 0; i < SAMPLES_PER_AXIS; i++) {
      for (let j = 0; j < SAMPLES_PER_AXIS; j++) {
        const x = selectionRect.left + selectionRect.width * (i + 0.5) / SAMPLES_PER_AXIS;
        const y = selectionRect.top + selectionRect.height * (j + 0.5) / SAMPLES_PER_AXIS;
        const el = document.elementsFromPoint(x, y)[0];
        if (el) counts.set(el, (counts.get(el) ?? 0) + 1);
      }
    }
    const total = SAMPLES_PER_AXIS * SAMPLES_PER_AXIS;
    const results = [];
    for (const [el, count] of counts) {
      const r = el.getBoundingClientRect();
      results.push({ el, coverage: count / total, area: Math.max(1, r.width * r.height) });
    }
    results.sort((a, b) => b.coverage - a.coverage || a.area - b.area);
    return results;
  }
  function describe(el) {
    const tag = el.tagName.toLowerCase();
    const id = el.id ? "#" + el.id : "";
    const cls = el.classList.length ? "." + Array.from(el.classList).join(".") : "";
    return tag + id + cls;
  }
  function matchSummary(matches) {
    const best = matches[0];
    const preview = (best.el.textContent ?? "").trim().replace(/\s+/g, " ").slice(0, 80);
    return `Selected: ${describe(best.el)}
content: "${preview}${preview.length === 80 ? "\u2026" : ""}"` + (matches.length > 1 ? `
(${matches.length - 1} other candidate(s) also in the box)` : "");
  }
  function startListening(rect, matches) {
    mode = "listening";
    let interim = "";
    showPanel(rect, `${matchSummary(matches)}

\u{1F3A4} Listening\u2026`);
    stt = createStt({
      onInterim(text) {
        interim = text;
        showPanel(rect, `${matchSummary(matches)}

\u{1F3A4} Listening\u2026 "${interim}"`);
      },
      onFinal(text) {
        void generateVisualization(rect, matches, text);
      },
      onError(message) {
        showPanel(rect, `${matchSummary(matches)}

\u26A0\uFE0F ${message}`);
      },
      onEnd() {
        stt = null;
        mode = "idle";
      }
    });
    void stt.start();
  }
  async function generateVisualization(rect, matches, transcript) {
    const best = matches[0];
    const selection = {
      tag: best.el.tagName.toLowerCase(),
      id: best.el.id || void 0,
      classes: best.el.classList.length ? Array.from(best.el.classList) : void 0,
      preview: (best.el.textContent ?? "").trim().replace(/\s+/g, " ").slice(0, 300)
    };
    showPanel(rect, `${matchSummary(matches)}

\u2705 Heard: "${transcript}"

\u2699\uFE0F Generating\u2026`);
    try {
      const imageBase64 = await activeImagePromise ?? void 0;
      const relay = await chrome.runtime.sendMessage({
        type: "generate",
        payload: { transcript, selection, imageBase64 }
      });
      if (!relay.ok || !relay.action) {
        showPanel(rect, `${matchSummary(matches)}

\u26A0\uFE0F Generation failed: ${relay.error ?? "unknown error"}`);
        return;
      }
      if (relay.action._type !== "createHtml") {
        showPanel(rect, `${matchSummary(matches)}

\u26A0\uFE0F Got an unexpected action type: ${relay.action._type}`);
        return;
      }
      showGeneratedVisualization(rect, relay.action, selection, transcript);
    } catch (e) {
      showPanel(rect, `${matchSummary(matches)}

\u26A0\uFE0F ${e instanceof Error ? e.message : "Generation failed"}`);
    }
  }
  var DRAG_HANDLE_HEIGHT = 22;
  var PANEL_W = 440;
  var PANEL_H = 340;
  var MIC_SIZE = 20;
  var REPORT_BTN_TITLE = "Report a problem (beta). Sends the developer: the page URL and title, what you circled, what you said, the generated HTML, any errors, and your browser version. Nothing is sent unless you click.";
  function showGeneratedVisualization(selectionRect, action, selection, transcript) {
    panelDragCleanup?.();
    panelVoiceCleanup?.();
    panelEl?.remove();
    const w = PANEL_W;
    const h = PANEL_H + DRAG_HANDLE_HEIGHT;
    const container = document.createElement("div");
    Object.assign(container.style, {
      position: "fixed",
      zIndex: "2147483647",
      width: w + "px",
      height: h + "px",
      background: "white",
      borderRadius: "8px",
      boxShadow: "0 4px 20px rgba(0,0,0,0.5)",
      overflow: "hidden",
      display: "flex",
      flexDirection: "column"
    });
    if (draggedPosition) {
      container.style.top = draggedPosition.top + "px";
      container.style.left = draggedPosition.left + "px";
    } else {
      container.style.top = Math.max(8, Math.min(selectionRect.bottom + 8, window.innerHeight - h - 8)) + "px";
      container.style.left = Math.min(Math.max(8, selectionRect.left), window.innerWidth - w - 8) + "px";
    }
    const header = document.createElement("div");
    Object.assign(header.style, {
      height: DRAG_HANDLE_HEIGHT + "px",
      flex: "0 0 auto",
      background: "#1a1a1a",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "0 4px",
      boxSizing: "border-box"
    });
    const reportBtn = document.createElement("button");
    reportBtn.textContent = "\u{1F41B}";
    reportBtn.title = REPORT_BTN_TITLE;
    Object.assign(reportBtn.style, {
      border: "none",
      background: "transparent",
      borderRadius: "4px",
      width: "18px",
      height: "18px",
      cursor: "pointer",
      fontSize: "11px",
      lineHeight: "1",
      transition: "background-color 0.1s"
    });
    reportBtn.addEventListener("mouseenter", () => {
      reportBtn.style.background = "rgba(255,255,255,0.15)";
    });
    reportBtn.addEventListener("mouseleave", () => {
      reportBtn.style.background = "transparent";
    });
    reportBtn.addEventListener("click", () => void sendBugReport());
    header.appendChild(reportBtn);
    const closeBtn = document.createElement("button");
    closeBtn.textContent = "\u2715";
    Object.assign(closeBtn.style, {
      border: "none",
      background: "transparent",
      color: "white",
      borderRadius: "4px",
      width: "18px",
      height: "18px",
      cursor: "pointer",
      fontSize: "11px",
      lineHeight: "1",
      transition: "background-color 0.1s"
    });
    closeBtn.addEventListener("mouseenter", () => {
      closeBtn.style.background = "rgba(255,255,255,0.15)";
    });
    closeBtn.addEventListener("mouseleave", () => {
      closeBtn.style.background = "transparent";
    });
    closeBtn.addEventListener("click", () => {
      panelDragCleanup?.();
      panelDragCleanup = null;
      panelVoiceCleanup?.();
      panelVoiceCleanup = null;
      container.remove();
    });
    header.appendChild(closeBtn);
    const iframe = document.createElement("iframe");
    Object.assign(iframe.style, { width: "100%", flex: "1 1 auto", border: "0", display: "block" });
    let currentHtml = action.html;
    let lastTranscript = transcript;
    let runtimeErrors = [];
    iframe.addEventListener("load", () => {
      iframe.contentWindow?.postMessage({ html: currentHtml }, "*");
    });
    function loadVisualization() {
      runtimeErrors = [];
      iframe.src = chrome.runtime.getURL("render.html") + "?t=" + Date.now();
    }
    loadVisualization();
    async function sendBugReport() {
      reportBtn.textContent = "\u2026";
      const payload = {
        selectionTag: selection.tag,
        selectionId: selection.id ?? "",
        selectionClasses: selection.classes?.join(" ") ?? "",
        selectionPreview: selection.preview ?? "",
        transcript: lastTranscript,
        html: currentHtml.slice(0, 2e4),
        runtimeErrors: runtimeErrors.join("\n") || "(none observed)",
        pageUrl: location.href,
        pageTitle: document.title,
        timestamp: (/* @__PURE__ */ new Date()).toISOString(),
        extensionVersion: chrome.runtime.getManifest().version,
        userAgent: navigator.userAgent
      };
      try {
        const relay = await chrome.runtime.sendMessage({
          type: "report-bug",
          payload
        });
        if (relay.ok) {
          reportBtn.textContent = "\u2705";
        } else if (relay.error === "not-configured") {
          await navigator.clipboard.writeText(JSON.stringify(payload, null, 2));
          reportBtn.textContent = "\u{1F4CB}";
          reportBtn.title = "Email reporting isn\u2019t set up yet - copied the report to your clipboard instead";
        } else {
          console.error("[report-bug] send failed:", relay.error);
          reportBtn.textContent = "\u26A0\uFE0F";
        }
      } catch (e) {
        console.error("[report-bug] send failed:", e);
        reportBtn.textContent = "\u26A0\uFE0F";
      }
      setTimeout(() => {
        reportBtn.textContent = "\u{1F41B}";
      }, 2e3);
    }
    const micBadge = document.createElement("div");
    micBadge.textContent = "\u{1F3A4}";
    Object.assign(micBadge.style, {
      position: "absolute",
      left: "6px",
      bottom: "6px",
      width: MIC_SIZE + "px",
      height: MIC_SIZE + "px",
      borderRadius: "50%",
      background: "#8a8a8a",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "10px",
      lineHeight: "1",
      boxShadow: "0 1px 4px rgba(0,0,0,0.4)",
      pointerEvents: "none",
      zIndex: "1",
      transition: "background-color 0.1s"
    });
    const generatingLabel = document.createElement("div");
    generatingLabel.textContent = "Generating\u2026";
    Object.assign(generatingLabel.style, {
      position: "absolute",
      left: 6 + MIC_SIZE + 6 + "px",
      bottom: "6px",
      height: MIC_SIZE + "px",
      lineHeight: MIC_SIZE + "px",
      padding: "0 10px",
      borderRadius: MIC_SIZE / 2 + "px",
      background: "rgba(0,0,0,0.72)",
      color: "white",
      fontFamily: "system-ui, sans-serif",
      fontSize: "11px",
      whiteSpace: "nowrap",
      boxShadow: "0 1px 4px rgba(0,0,0,0.4)",
      pointerEvents: "none",
      zIndex: "1",
      display: "none"
    });
    let iterateStt = null;
    async function iterateVisualization(transcript2) {
      generatingLabel.style.display = "block";
      lastTranscript = transcript2;
      try {
        const relay = await chrome.runtime.sendMessage({
          type: "generate",
          payload: { transcript: transcript2, selection, previousHtml: currentHtml }
        });
        if (!relay.ok || !relay.action || relay.action._type !== "createHtml") {
          console.error("[iterate] generation failed:", relay.error ?? relay.action?._type);
          return;
        }
        currentHtml = relay.action.html;
        loadVisualization();
      } catch (e) {
        console.error("[iterate] request failed:", e);
      } finally {
        generatingLabel.style.display = "none";
      }
    }
    function startIterateCapture() {
      if (iterateStt) return;
      micBadge.style.background = "#ef4444";
      let interimText = "";
      let gotFinal = false;
      iterateStt = createStt({
        onInterim(text) {
          interimText = text;
        },
        onFinal(text) {
          gotFinal = true;
          void iterateVisualization(text);
        },
        onError(message) {
          console.error("[iterate]", message);
          micBadge.style.background = "#d97706";
          setTimeout(() => {
            micBadge.style.background = "#8a8a8a";
          }, 600);
        },
        onEnd() {
          iterateStt = null;
          micBadge.style.background = "#8a8a8a";
          if (!gotFinal && interimText.trim()) void iterateVisualization(interimText.trim());
        }
      });
      void iterateStt.start();
    }
    function stopIterateCapture() {
      iterateStt?.stop();
    }
    function onIterateKeyDown(e) {
      if (e.key.toLowerCase() !== "v" || iterateStt) return;
      if (!container.matches(":hover")) return;
      const active = document.activeElement;
      const isTyping = active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement || active instanceof HTMLElement && active.isContentEditable;
      if (isTyping) return;
      e.preventDefault();
      startIterateCapture();
    }
    function onIterateKeyUp(e) {
      if (e.key.toLowerCase() !== "v") return;
      stopIterateCapture();
    }
    function onIframeMessage(e) {
      if (e.source !== iframe.contentWindow) return;
      if (e.data?.type === "iterate-key-down") startIterateCapture();
      else if (e.data?.type === "iterate-key-up") stopIterateCapture();
      else if (e.data?.type === "runtime-error" && typeof e.data.message === "string") {
        runtimeErrors.push(e.data.message);
        if (runtimeErrors.length > 10) runtimeErrors.shift();
      }
    }
    document.addEventListener("keydown", onIterateKeyDown);
    document.addEventListener("keyup", onIterateKeyUp);
    window.addEventListener("message", onIframeMessage);
    panelVoiceCleanup = () => {
      document.removeEventListener("keydown", onIterateKeyDown);
      document.removeEventListener("keyup", onIterateKeyUp);
      window.removeEventListener("message", onIframeMessage);
      iterateStt?.abort();
      iterateStt = null;
    };
    container.appendChild(header);
    container.appendChild(iframe);
    container.appendChild(micBadge);
    container.appendChild(generatingLabel);
    document.documentElement.appendChild(container);
    panelEl = container;
    panelDragCleanup = makeDraggable(container, header);
  }
  function showPanel(selectionRect, text) {
    panelDragCleanup?.();
    panelEl?.remove();
    const panel = document.createElement("div");
    Object.assign(panel.style, {
      position: "fixed",
      zIndex: "2147483647",
      maxWidth: "420px",
      background: "#1c1c1f",
      color: "#e5e5e5",
      padding: "12px 14px",
      borderRadius: "10px",
      borderLeft: "3px solid #3b82f6",
      fontFamily: "system-ui, sans-serif",
      fontSize: "12.5px",
      lineHeight: "1.6",
      boxShadow: "0 6px 20px rgba(0,0,0,0.4)",
      whiteSpace: "pre-wrap",
      overflowY: "auto"
    });
    if (draggedPosition) {
      panel.style.top = draggedPosition.top + "px";
      panel.style.left = draggedPosition.left + "px";
      panel.style.maxHeight = Math.max(100, window.innerHeight - draggedPosition.top - 8) + "px";
    } else {
      const margin = 8;
      const spaceBelow = window.innerHeight - selectionRect.bottom - margin;
      const spaceAbove = selectionRect.top - margin;
      const placeAbove = spaceBelow < 120 && spaceAbove > spaceBelow;
      panel.style.maxHeight = Math.max(100, (placeAbove ? spaceAbove : spaceBelow) - margin) + "px";
      if (placeAbove) {
        panel.style.bottom = window.innerHeight - selectionRect.top + margin + "px";
      } else {
        panel.style.top = selectionRect.bottom + margin + "px";
      }
      panel.style.left = Math.min(Math.max(8, selectionRect.left), window.innerWidth - 440) + "px";
    }
    panel.textContent = text;
    document.documentElement.appendChild(panel);
    panelEl = panel;
    panel.scrollTop = panel.scrollHeight;
    panelDragCleanup = makeDraggable(panel);
  }
  chrome.runtime.onMessage.addListener((message) => {
    if (message?.type !== "toggle-overlay") return;
    if (mode !== "idle") closeEverything();
    else enterSelectMode();
  });
})();
