// GENERATED by extension/build.mjs - do not edit directly.
"use strict";
(() => {
  // extension/src/options.ts
  var apiKeyInput = document.getElementById("apiKey");
  var saveButton = document.getElementById("save");
  var statusEl = document.getElementById("status");
  chrome.storage.local.get("geminiApiKey").then(({ geminiApiKey }) => {
    if (typeof geminiApiKey === "string") apiKeyInput.value = geminiApiKey;
  });
  saveButton.addEventListener("click", async () => {
    await chrome.storage.local.set({ geminiApiKey: apiKeyInput.value.trim() });
    statusEl.textContent = "Saved.";
    setTimeout(() => {
      statusEl.textContent = "";
    }, 2e3);
  });
})();
