// GENERATED by extension/build.mjs - do not edit directly.
"use strict";
(() => {
  // extension/src/render.ts
  function attachKeyForwarding() {
    document.addEventListener("keydown", (e) => {
      if (e.key.toLowerCase() !== "v") return;
      const active = document.activeElement;
      const isTyping = active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement || active instanceof HTMLElement && active.isContentEditable;
      if (isTyping) return;
      window.parent.postMessage({ type: "iterate-key-down" }, "*");
    });
    document.addEventListener("keyup", (e) => {
      if (e.key.toLowerCase() !== "v") return;
      window.parent.postMessage({ type: "iterate-key-up" }, "*");
    });
  }
  function attachErrorForwarding() {
    window.addEventListener("error", (e) => {
      window.parent.postMessage({ type: "runtime-error", message: e.message }, "*");
    });
    window.addEventListener("unhandledrejection", (e) => {
      window.parent.postMessage({ type: "runtime-error", message: `Unhandled rejection: ${e.reason}` }, "*");
    });
  }
  window.addEventListener("message", (event) => {
    const raw = event.data?.html;
    if (typeof raw !== "string") return;
    const html = raw.replace(/^\s*<!doctype[^>]*>/i, "").trimStart();
    document.open();
    document.write("<!DOCTYPE html>\n" + html);
    document.close();
    attachKeyForwarding();
    attachErrorForwarding();
  });
})();
